from sqlalchemy import text

_GET_MOST_RECENT_AVG_WT_NATIONWIDE = """
SELECT ROUND(AVG(WT)) FROM DIRTYOBS
JOIN (
	SELECT MID, MAX(DT) AS RECENT_DT FROM DIRTYOBS GROUP BY MID
) AS RECENT_PER_MID
ON DIRTYOBS.MID = RECENT_PER_MID.MID
AND DIRTYOBS.DT = RECENT_PER_MID.RECENT_DT;
"""

GET_MOST_RECENT_AVG_WT_NATIONWIDE = text(_GET_MOST_RECENT_AVG_WT_NATIONWIDE)